import type { AssignmentWorkspaceData } from "./types";

const WORKSPACES: Record<string, AssignmentWorkspaceData> = {
  "assignment-quantum-gates": {
    id: "assignment-quantum-gates",
    courseTagLabel: "Physics • Mod 3",
    title: "Quantum Gates Implementation",
    timeRemainingLabel: "00:45:12",
    savedLabel: "Saved 2s ago",
    daysLeftLabel: "3 days left",
    dueLabel: "Oct 24, 11:59 PM",
    description:
      "In this assignment, you will implement the core single-qubit quantum gates (Pauli-X, Y, Z, and Hadamard) using the Qiskit library. Ensure that your implementations pass the provided unit tests in utils.py.",
    requirements: [
      { id: "req-init", label: "Initialize QuantumCircuit", done: true },
      { id: "req-x", label: "Implement Pauli-X gate sequence", done: false },
      { id: "req-h", label: "Apply Hadamard transformation", done: false },
      { id: "req-state", label: "Return statevector results", done: false },
    ],
    resources: [
      {
        id: "res-qiskit",
        title: "Qiskit Documentation",
        metaLabel: "PDF • 2.4 MB",
        tone: "primary",
      },
      {
        id: "res-setup",
        title: "Environment Setup Guide",
        metaLabel: "Link",
        tone: "secondary",
      },
      {
        id: "res-gates",
        title: "Single-Qubit Gates Cheatsheet",
        metaLabel: "PDF • 620 KB",
        tone: "secondary",
      },
      {
        id: "res-statevector",
        title: "Statevector Simulation Notes",
        metaLabel: "Link",
        tone: "secondary",
      },
      {
        id: "res-rubric",
        title: "Grading Rubric",
        metaLabel: "PDF • 310 KB",
        tone: "secondary",
      },
    ],
    progressPercent: 65,
    progressWidthClassName: "w-[65%]",
    progressLabel: "2 of 4 requirements met",
    editor: {
      tabs: [
        { id: "main.py", label: "main.py", kind: "python", isDirty: true },
        { id: "utils.py", label: "utils.py", kind: "data" },
      ],
      files: {
        "main.py": [
          "from qiskit import QuantumCircuit",
          "import numpy as np",
          "",
          "# Initialize a 2-qubit quantum circuit",
          "def implement_gates():",
          "    qc = QuantumCircuit(2)",
          "",
          "    # TODO: Apply a Pauli-X gate to the first qubit",
          "    qc.x(0)",
          "",
          "    # TODO: Apply a Hadamard gate to the second qubit",
          "    qc.h(1)",
          "",
          "    # TODO: Apply Y and Z gates for completeness",
          "    # qc.y(0)",
          "    # qc.z(1)",
          "",
          "    # Optional: inspect circuit",
          "    # print(qc)",
          "",
          "    # TODO: add helper functions for each gate",
          "    # def apply_x(qc, qubit): qc.x(qubit)",
          "    # def apply_y(qc, qubit): qc.y(qubit)",
          "    # def apply_z(qc, qubit): qc.z(qubit)",
          "    # def apply_h(qc, qubit): qc.h(qubit)",
          "",
          "    # TODO: run the circuit on a statevector simulator",
          "    # from qiskit_aer import Aer",
          "    # backend = Aer.get_backend('statevector_simulator')",
          "    # result = backend.run(qc).result()",
          "    # statevector = result.get_statevector()",
          "",
          "    # TODO: return both circuit and statevector",
          "    # return qc, np.asarray(statevector)",
          "",
          "    # Notes:",
          "    # - Validate shapes and normalization",
          "    # - Ensure deterministic output",
          "    # - Add simple test vectors",
          "    #",
          "    # Example checks:",
          "    # assert np.isclose(np.linalg.norm(statevector), 1.0)",
          "    # assert statevector.shape == (4,)",
          "",
          "    # Stretch goal: add a small CLI",
          "    # - parse args for gate sequence",
          "    # - output statevector and circuit diagram",
          "",
          "    return qc",
          "",
          "if __name__ == '__main__':",
          "    circuit = implement_gates()",
          "    print(circuit.draw())",
        ],
        "utils.py": [
          "# utils.py (mock)",
          "# Provided tests will be displayed here.",
          "",
          "def assert_close(a, b, tol=1e-6):",
          "    return abs(a - b) < tol",
          "",
          "# TODO: Add unit tests for X/Y/Z/H gates",
        ],
      },
      consoleOutput: [
        "❯ Executing main.py...",
        "[info] python main.py",
        "[info] building circuit...",
        "",
        "     ┌───┐",
        "q_0: ┤ X ├",
        "     ├───┤",
        "q_1: ┤ H ├",
        "     └───┘",
        "",
        "✓ Tests passed: 1/3 successful",
        "✗ Missing: statevector output (expected numpy array)",
      ],
    },
    tutor: {
      message: {
        text: "It looks like you've successfully applied the X and H gates! The final step is returning the statevector results. Need a hint on how to extract that from the simulator?",
      },
      suggestions: [
        { id: "suggest-statevector", label: "How to get statevector?" },
        { id: "suggest-pauli", label: "Explain Pauli-X" },
      ],
    },
  },

  "assignment-bloch-sphere": {
    id: "assignment-bloch-sphere",
    courseTagLabel: "Physics • Mod 3",
    title: "Visualize Bloch Sphere Rotations",
    timeRemainingLabel: "01:12:04",
    savedLabel: "Saved 18s ago",
    daysLeftLabel: "1 day left",
    dueLabel: "Oct 20, 11:59 PM",
    description:
      "In this assignment, you'll simulate single-qubit rotations and plot Bloch vectors across time steps. Ensure that your notebook includes both the plots and a brief explanation of the geometry in utils.py.",
    requirements: [
      { id: "req-rot", label: "Simulate rotation sequence", done: true },
      { id: "req-plot", label: "Plot Bloch vectors over time", done: false },
      {
        id: "req-writeup",
        label: "Write-up: geometric interpretation",
        done: false,
      },
    ],
    resources: [
      {
        id: "res-bloch",
        title: "Bloch Sphere Cheatsheet",
        metaLabel: "PDF • 1.1 MB",
        tone: "primary",
      },
      {
        id: "res-matplotlib",
        title: "Matplotlib Quickstart",
        metaLabel: "Link",
        tone: "secondary",
      },
      {
        id: "res-rotation",
        title: "Rotation Gates Reference",
        metaLabel: "PDF • 740 KB",
        tone: "secondary",
      },
      {
        id: "res-samples",
        title: "Sample Plots Gallery",
        metaLabel: "Link",
        tone: "secondary",
      },
    ],
    progressPercent: 33,
    progressWidthClassName: "w-1/3",
    progressLabel: "1 of 3 requirements met",
    editor: {
      tabs: [
        { id: "main.py", label: "main.py", kind: "python", isDirty: true },
        { id: "utils.py", label: "utils.py", kind: "data" },
      ],
      files: {
        "main.py": [
          "from qiskit import QuantumCircuit",
          "import numpy as np",
          "",
          "def rotate_and_measure(theta):",
          "    qc = QuantumCircuit(1)",
          "    qc.ry(theta, 0)",
          "    return qc",
          "",
          "def sweep():",
          "    thetas = np.linspace(0, 2*np.pi, 20)",
          "    circuits = [rotate_and_measure(t) for t in thetas]",
          "    return circuits",
          "",
          "if __name__ == '__main__':",
          "    circuits = sweep()",
          "    print(len(circuits))",
          "",
          "# TODO: extract statevectors and compute Bloch vectors",
          "# TODO: plot x(t), y(t), z(t)",
        ],
        "utils.py": [
          "# utils.py (mock)",
          "# Helper functions for Bloch vector extraction.",
          "",
          "def bloch_from_statevector(state):",
          "    # placeholder",
          "    return (0.0, 0.0, 1.0)",
        ],
      },
      consoleOutput: [
        "❯ Executing main.py...",
        "✓ Tests passed: 0/3 successful",
      ],
    },
    tutor: {
      message: {
        text: "Nice start. Next, try extracting the Bloch vector from the statevector after each rotation and plot it as a trajectory.",
      },
      suggestions: [
        { id: "suggest-bloch", label: "How do I get Bloch vector?" },
        { id: "suggest-rot", label: "Explain rotation gates" },
      ],
    },
  },

  "assignment-entanglement-analysis": {
    id: "assignment-entanglement-analysis",
    courseTagLabel: "Physics • Mod 4",
    title: "Entanglement Analysis",
    timeRemainingLabel: "04:08:21",
    savedLabel: "Saved 2m ago",
    daysLeftLabel: "7 days left",
    dueLabel: "Oct 31, 11:59 PM",
    description:
      "Build a Bell-state circuit, compute measurement correlations, and write a short essay discussing non-locality and information-theoretic implications. Use utils.py for the required checks.",
    requirements: [
      { id: "req-bell", label: "Construct Bell state circuit", done: false },
      { id: "req-corr", label: "Compute correlation matrix", done: false },
      {
        id: "req-essay",
        label: "Write-up: non-locality discussion",
        done: false,
      },
    ],
    resources: [
      {
        id: "res-paper",
        title: "Bell Inequalities Primer",
        metaLabel: "PDF • 900 KB",
        tone: "primary",
      },
      {
        id: "res-template",
        title: "Essay Template",
        metaLabel: "Link",
        tone: "secondary",
      },
    ],
    progressPercent: 0,
    progressWidthClassName: "w-0",
    progressLabel: "0 of 3 requirements met",
    editor: {
      tabs: [
        { id: "main.py", label: "main.py", kind: "python", isDirty: false },
        { id: "utils.py", label: "utils.py", kind: "data" },
      ],
      files: {
        "main.py": [
          "from qiskit import QuantumCircuit",
          "",
          "def bell_pair():",
          "    qc = QuantumCircuit(2)",
          "    qc.h(0)",
          "    qc.cx(0, 1)",
          "    return qc",
          "",
          "if __name__ == '__main__':",
          "    print(bell_pair().draw())",
        ],
        "utils.py": ["# utils.py (mock)", "# Add correlation checks here."],
      },
      consoleOutput: ["Ready. Click Run Code to execute."],
    },
    tutor: {
      message: {
        text: "Start by preparing a Bell pair, then compute correlations for X and Z measurements. After that, connect results to the CHSH inequality in your write-up.",
      },
      suggestions: [
        { id: "suggest-chsh", label: "What is CHSH?" },
        { id: "suggest-corr", label: "How to compute correlations?" },
      ],
    },
  },

  "assignment-noise-models": {
    id: "assignment-noise-models",
    courseTagLabel: "Physics • Mod 5",
    title: "Noise Models & Error Mitigation",
    timeRemainingLabel: "02:26:55",
    savedLabel: "Saved just now",
    daysLeftLabel: "14 days left",
    dueLabel: "Nov 6, 11:59 PM",
    description:
      "Add a depolarizing noise model, compare ideal vs noisy outcomes, and briefly discuss mitigation strategies. Ensure your figures and analysis match the rubric in utils.py.",
    requirements: [
      { id: "req-noise", label: "Implement depolarizing noise", done: false },
      {
        id: "req-compare",
        label: "Compare ideal vs noisy results",
        done: false,
      },
      {
        id: "req-mitigate",
        label: "Describe mitigation strategy",
        done: false,
      },
      { id: "req-plot", label: "Plot error vs noise strength", done: false },
    ],
    resources: [
      {
        id: "res-noise",
        title: "Noise Modeling Notes",
        metaLabel: "PDF • 1.8 MB",
        tone: "primary",
      },
      {
        id: "res-aer",
        title: "Aer Noise API",
        metaLabel: "Link",
        tone: "secondary",
      },
    ],
    progressPercent: 0,
    progressWidthClassName: "w-0",
    progressLabel: "0 of 4 requirements met",
    editor: {
      tabs: [
        { id: "main.py", label: "main.py", kind: "python", isDirty: false },
        { id: "utils.py", label: "utils.py", kind: "data" },
      ],
      files: {
        "main.py": [
          "# TODO: configure a depolarizing noise model",
          "# TODO: run circuits with and without noise",
          "# TODO: plot fidelity vs noise strength",
        ],
        "utils.py": ["# utils.py (mock)", "# rubric + checks"],
      },
      consoleOutput: ["Ready."],
    },
    tutor: {
      message: {
        text: "Begin with a simple single-qubit circuit, then add depolarizing noise and compare the output distribution. Plot fidelity as you sweep noise strength.",
      },
      suggestions: [
        { id: "suggest-noise", label: "What is depolarizing noise?" },
        { id: "suggest-fidelity", label: "How to compute fidelity?" },
      ],
    },
  },

  "assignment-qft": {
    id: "assignment-qft",
    courseTagLabel: "Physics • Mod 6",
    title: "Quantum Fourier Transform",
    timeRemainingLabel: "03:05:40",
    savedLabel: "Saved 1m ago",
    daysLeftLabel: "21 days left",
    dueLabel: "Nov 13, 11:59 PM",
    description:
      "Implement a QFT circuit and verify correctness on small basis states. Include a short explanation of phase kickback and how it appears inside the transform.",
    requirements: [
      { id: "req-qft", label: "Implement QFT on n qubits", done: false },
      { id: "req-inv", label: "Implement inverse QFT", done: false },
      { id: "req-tests", label: "Verify with test vectors", done: false },
    ],
    resources: [
      {
        id: "res-qft",
        title: "QFT Reference",
        metaLabel: "PDF • 1.3 MB",
        tone: "primary",
      },
      {
        id: "res-phases",
        title: "Phase Kickback Notes",
        metaLabel: "Link",
        tone: "secondary",
      },
    ],
    progressPercent: 0,
    progressWidthClassName: "w-0",
    progressLabel: "0 of 3 requirements met",
    editor: {
      tabs: [
        { id: "main.py", label: "main.py", kind: "python", isDirty: false },
        { id: "utils.py", label: "utils.py", kind: "data" },
      ],
      files: {
        "main.py": [
          "from qiskit import QuantumCircuit",
          "import numpy as np",
          "",
          "def qft(n):",
          "    qc = QuantumCircuit(n)",
          "    # TODO: implement QFT",
          "    return qc",
          "",
          "def iqft(n):",
          "    qc = QuantumCircuit(n)",
          "    # TODO: implement inverse QFT",
          "    return qc",
          "",
          "if __name__ == '__main__':",
          "    print(qft(3).draw())",
        ],
        "utils.py": ["# utils.py (mock)", "# tests will be shown here"],
      },
      consoleOutput: ["Ready."],
    },
    tutor: {
      message: {
        text: "Start with n=3. Implement the pattern: H on qubit i, then controlled phase rotations from j>i. Swap qubits at the end.",
      },
      suggestions: [
        { id: "suggest-qft", label: "QFT gate pattern" },
        { id: "suggest-rot", label: "Controlled phase rotations" },
      ],
    },
  },

  "assignment-grover": {
    id: "assignment-grover",
    courseTagLabel: "Physics • Mod 6",
    title: "Grover Search Walkthrough",
    timeRemainingLabel: "02:50:11",
    savedLabel: "Saved 9m ago",
    daysLeftLabel: "23 days left",
    dueLabel: "Nov 15, 11:59 PM",
    description:
      "Explain oracle construction and the diffusion operator, then simulate Grover iterations on a small search space. Include expected iteration count and a brief discussion of amplitude amplification.",
    requirements: [
      {
        id: "req-oracle",
        label: "Build an oracle for 1 marked item",
        done: false,
      },
      { id: "req-diff", label: "Implement diffusion operator", done: false },
      {
        id: "req-sim",
        label: "Simulate iterations and plot success",
        done: false,
      },
      { id: "req-write", label: "Write-up: iteration count", done: false },
    ],
    resources: [
      {
        id: "res-grover",
        title: "Grover Algorithm Overview",
        metaLabel: "PDF • 1.0 MB",
        tone: "primary",
      },
      {
        id: "res-amplitude",
        title: "Amplitude Amplification",
        metaLabel: "Link",
        tone: "secondary",
      },
    ],
    progressPercent: 0,
    progressWidthClassName: "w-0",
    progressLabel: "0 of 4 requirements met",
    editor: {
      tabs: [
        { id: "main.py", label: "main.py", kind: "python", isDirty: false },
        { id: "utils.py", label: "utils.py", kind: "data" },
      ],
      files: {
        "main.py": [
          "from qiskit import QuantumCircuit",
          "",
          "def oracle(n):",
          "    qc = QuantumCircuit(n)",
          "    # TODO: mark target state",
          "    return qc",
          "",
          "def diffuser(n):",
          "    qc = QuantumCircuit(n)",
          "    # TODO: implement inversion about the mean",
          "    return qc",
          "",
          "def grover_iteration(n):",
          "    qc = QuantumCircuit(n)",
          "    qc.compose(oracle(n), inplace=True)",
          "    qc.compose(diffuser(n), inplace=True)",
          "    return qc",
        ],
        "utils.py": ["# utils.py (mock)", "# checks + rubric"],
      },
      consoleOutput: ["Ready."],
    },
    tutor: {
      message: {
        text: "Pick n=2 or n=3 first. Implement the diffuser via H, X, multi-controlled Z, then X, H. Then plot success probability per iteration.",
      },
      suggestions: [
        { id: "suggest-diffuser", label: "Diffuser construction" },
        { id: "suggest-iter", label: "How many iterations?" },
      ],
    },
  },
};

export function getAssignmentWorkspaceById(
  assignmentId: string,
): AssignmentWorkspaceData | undefined {
  return WORKSPACES[assignmentId];
}
