import type {
  ClassListHeaderData,
  ClassListMember,
  ClassListStatsData,
} from "./types";

export const CLASS_LIST_HEADER: ClassListHeaderData = {
  classId: "advanced-physics",
  title: "Advanced Physics",
  leadInstructorName: "Dr. Sarah Chen",
  leadInstructorAvatarUrl:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDrOe9fdHXTFPxCtRwV1tcub5Ty7phOwT0y5Funkp8TE3TPQH2zmjqvDVQ1f2-OyL6Ek0ToIgKFwFqtZvHcvCn7cLNNaY8JJi3M6GIecRnGbAJ85aSXVhhYMGBLtLNqJm3LXn4l7QT7HG8HhMNSNvFUFxJ2bjOy_gPSuMkwwgEjtUPjfTpfue6yiOK1KpyONzrtf1aILsV0L2RBN8wnkY_jAG1HBd0h5gv3Hh6L0idxnusaWXifKsNB03DRQN5Q-BRuB3cuss_yQm8I",
};

export const CLASS_LIST_STATS: ClassListStatsData = {
  totalMembers: { value: 142, deltaLabel: "+4%" },
  activeNow: 28,
  avgProgressPct: 76,
  completionRatePct: 84,
  atRisk: 12,
};

export const CLASS_LIST_MEMBERS: ClassListMember[] = [
  {
    id: "elena-rodriguez",
    name: "Elena Rodriguez",
    email: "e.rodriguez@university.edu",
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCk65VdyNOTVHGKlA6CsmdFuuYQQ730olk0uYWClbakIR6M6Pe6MDMiCrbHFZ7UANLPjPeqvom0t9a3Zpax963No1FVBwsUYDx_DXggEj2GXN9dw__-LjR-Uiw6Cf99lZJTgsnhyDSFz9jJfKIJdHznScfoXiZ1az-1-V83u5mN_mSZyNJxjAaKCgoSWDE1qfN61qSEGKzXmiKkTta_jBV0b2IO78xnX4l5dcnFXet-UBExvwpCPn-YPJNe3Q7xiE9_x2-HiHtqnD_G",
    tag: { label: "Top Performer", tone: "success" },
    role: "Student",
    isActive: true,
    progressPct: 94,
    activity: { label: "2m ago", tone: "online" },
  },
  {
    id: "marcus-thorne",
    name: "Marcus Thorne",
    email: "m.thorne@university.edu",
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDxwG1PV2jiTEzRxEsAyjHykk1vOBpezjy3ALIhJpbQ2_NRofaXbYIGLV5ZjVUFmg98ickXHspqI9cFhSB6VjXvJmQWKszlFFA1h01tVo7lh-DqW79YfvLor2z4fwcAtX2nwjimQK0uxTXZ78TaN8hQYWZRkZzGXz-7wR0vZXDF3SY1CP3Fzw81oN2OAqZeY9Jkp3qQoODP-fgCxGEXvCC3KFRdwBn-Ht4YiqiXu6p45VUA4m4Uae-P5bDO_SAnxkDBkwhktKqDkbc2",
    tag: { label: "At Risk", tone: "danger" },
    role: "Student",
    isActive: true,
    progressPct: 42,
    activity: { label: "3h ago", tone: "recent" },
  },
  {
    id: "amara-okafor",
    name: "Amara Okafor",
    email: "a.okafor@university.edu",
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCfKQmltA0W913nWxjVRjznVh2cRV1XxGjKlyKmw4h2g5wqC2NQlTVlvvgYk-0B43N7RpdVELCidkK3Feqz6QX6RFYQJwuWJg1nVVKw0H4WMvRFtLjc7yd4-YtL3KVVx854zm436-bWkcWU36nkFX5DSZf1jtuX0bvDiaO6J9M1d_ooGmMXvFKe8_ztY4Fy6ZoaGQ7ZGmoGhi8bh0YZxfH0SDWmR0O_60K8Q0jlED5BvrcgfTMjasbNfhAyTrk0VnLVL1jS-1c8Fip8",
    tag: { label: "New", tone: "info" },
    role: "TA",
    isActive: true,
    progressPct: 78,
    activity: { label: "Active now", tone: "online" },
  },
  {
    id: "arthur-sterling",
    name: "Arthur Sterling",
    email: "a.sterling@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=22",
    role: "Lecturer",
    isActive: true,
    progressPct: 88,
    activity: { label: "1d ago", tone: "recent" },
  },
  {
    id: "julian-vane",
    name: "Julian Vane",
    email: "j.vane@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=12",
    role: "Lecturer",
    isActive: true,
    progressPct: 63,
    activity: { label: "6h ago", tone: "recent" },
  },
  {
    id: "nina-park",
    name: "Nina Park",
    email: "n.park@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=44",
    tag: { label: "Top Performer", tone: "success" },
    role: "Student",
    isActive: true,
    progressPct: 91,
    activity: { label: "10m ago", tone: "online" },
  },
  {
    id: "diego-ramirez",
    name: "Diego Ramirez",
    email: "d.ramirez@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=18",
    role: "Student",
    isActive: true,
    progressPct: 55,
    activity: { label: "2h ago", tone: "recent" },
  },
  {
    id: "fatima-hassan",
    name: "Fatima Hassan",
    email: "f.hassan@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=5",
    tag: { label: "At Risk", tone: "danger" },
    role: "Student",
    isActive: true,
    progressPct: 39,
    activity: { label: "30m ago", tone: "recent" },
  },
  {
    id: "liam-obrien",
    name: "Liam O'Brien",
    email: "l.obrien@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=9",
    role: "Student",
    isActive: true,
    progressPct: 72,
    activity: { label: "Active now", tone: "online" },
  },
  {
    id: "sofia-martinez",
    name: "Sofia Martinez",
    email: "s.martinez@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=29",
    tag: { label: "New", tone: "info" },
    role: "Student",
    isActive: true,
    progressPct: 67,
    activity: { label: "1h ago", tone: "recent" },
  },
  {
    id: "kevin-lee",
    name: "Kevin Lee",
    email: "k.lee@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=15",
    role: "Student",
    isActive: true,
    progressPct: 81,
    activity: { label: "5m ago", tone: "online" },
  },
  {
    id: "maya-singh",
    name: "Maya Singh",
    email: "m.singh@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=16",
    tag: { label: "Top Performer", tone: "success" },
    role: "Student",
    isActive: true,
    progressPct: 96,
    activity: { label: "Active now", tone: "online" },
  },
  {
    id: "olivia-chen",
    name: "Olivia Chen",
    email: "o.chen@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=17",
    role: "Student",
    isActive: true,
    progressPct: 74,
    activity: { label: "40m ago", tone: "recent" },
  },
  {
    id: "hassan-ali",
    name: "Hassan Ali",
    email: "h.ali@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=19",
    tag: { label: "At Risk", tone: "danger" },
    role: "Student",
    isActive: false,
    progressPct: 28,
    activity: { label: "2d ago", tone: "recent" },
  },
  {
    id: "emma-johnson",
    name: "Emma Johnson",
    email: "e.johnson@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=21",
    role: "TA",
    isActive: true,
    progressPct: 79,
    activity: { label: "3h ago", tone: "recent" },
  },
  {
    id: "noah-wilson",
    name: "Noah Wilson",
    email: "n.wilson@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=24",
    role: "Student",
    isActive: true,
    progressPct: 58,
    activity: { label: "1h ago", tone: "recent" },
  },
  {
    id: "ava-kim",
    name: "Ava Kim",
    email: "a.kim@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=25",
    tag: { label: "New", tone: "info" },
    role: "Student",
    isActive: true,
    progressPct: 61,
    activity: { label: "20m ago", tone: "recent" },
  },
  {
    id: "ethan-brooks",
    name: "Ethan Brooks",
    email: "e.brooks@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=26",
    role: "Student",
    isActive: true,
    progressPct: 49,
    activity: { label: "6h ago", tone: "recent" },
  },
  {
    id: "isabella-nguyen",
    name: "Isabella Nguyen",
    email: "i.nguyen@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=27",
    tag: { label: "Top Performer", tone: "success" },
    role: "Student",
    isActive: true,
    progressPct: 93,
    activity: { label: "12m ago", tone: "online" },
  },
  {
    id: "lucas-patel",
    name: "Lucas Patel",
    email: "l.patel@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=28",
    role: "Student",
    isActive: true,
    progressPct: 66,
    activity: { label: "2h ago", tone: "recent" },
  },
  {
    id: "mia-carter",
    name: "Mia Carter",
    email: "m.carter@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=30",
    role: "Student",
    isActive: true,
    progressPct: 83,
    activity: { label: "Active now", tone: "online" },
  },
  {
    id: "jack-morgan",
    name: "Jack Morgan",
    email: "j.morgan@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=31",
    role: "TA",
    isActive: true,
    progressPct: 71,
    activity: { label: "15m ago", tone: "online" },
  },
  {
    id: "zoe-adams",
    name: "Zoe Adams",
    email: "z.adams@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=33",
    tag: { label: "New", tone: "info" },
    role: "Student",
    isActive: true,
    progressPct: 64,
    activity: { label: "3h ago", tone: "recent" },
  },
  {
    id: "ryan-cooper",
    name: "Ryan Cooper",
    email: "r.cooper@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=34",
    role: "Student",
    isActive: true,
    progressPct: 52,
    activity: { label: "1d ago", tone: "recent" },
  },
  {
    id: "grace-li",
    name: "Grace Li",
    email: "g.li@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=35",
    tag: { label: "Top Performer", tone: "success" },
    role: "Student",
    isActive: true,
    progressPct: 97,
    activity: { label: "8m ago", tone: "online" },
  },
  {
    id: "samuel-green",
    name: "Samuel Green",
    email: "s.green@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=36",
    role: "Student",
    isActive: true,
    progressPct: 57,
    activity: { label: "4h ago", tone: "recent" },
  },
  {
    id: "chloe-turner",
    name: "Chloe Turner",
    email: "c.turner@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=37",
    tag: { label: "At Risk", tone: "danger" },
    role: "Student",
    isActive: true,
    progressPct: 41,
    activity: { label: "2h ago", tone: "recent" },
  },
  {
    id: "leo-roberts",
    name: "Leo Roberts",
    email: "l.roberts@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=38",
    role: "Student",
    isActive: true,
    progressPct: 69,
    activity: { label: "25m ago", tone: "recent" },
  },
  {
    id: "aisha-bello",
    name: "Aisha Bello",
    email: "a.bello@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=39",
    role: "Student",
    isActive: true,
    progressPct: 77,
    activity: { label: "Active now", tone: "online" },
  },
  {
    id: "benjamin-clark",
    name: "Benjamin Clark",
    email: "b.clark@university.edu",
    avatarUrl: "https://i.pravatar.cc/80?img=40",
    role: "Student",
    isActive: true,
    progressPct: 62,
    activity: { label: "50m ago", tone: "recent" },
  },
];
